package e.a.b.c;

/* loaded from: classes.dex */
public final class b {
    public static final e.a.b.c.b.a A;
    public static final e.a.b.c.b.a A0;
    public static final e.a.b.c.b.a A1;
    public static final e.a.b.c.b.a A2;
    public static final e.a.b.c.b.a B;
    public static final e.a.b.c.b.a B0;
    public static final e.a.b.c.b.a B1;
    public static final e.a.b.c.b.a B2;
    public static final e.a.b.c.b.a C;
    public static final e.a.b.c.b.a C0;
    public static final e.a.b.c.b.a C1;
    public static final e.a.b.c.b.a C2;
    public static final e.a.b.c.b.a D;
    public static final e.a.b.c.b.a D0;
    public static final e.a.b.c.b.a D1;
    public static final e.a.b.c.b.a D2;
    public static final e.a.b.c.b.a E;
    public static final e.a.b.c.b.a E0;
    public static final e.a.b.c.b.a E1;
    public static final e.a.b.c.b.a E2;
    public static final e.a.b.c.b.a F;
    public static final e.a.b.c.b.a F0;
    public static final e.a.b.c.b.a F1;
    public static final e.a.b.c.b.a F2;
    public static final e.a.b.c.b.a G;
    public static final e.a.b.c.b.a G0;
    public static final e.a.b.c.b.a G1;
    public static final e.a.b.c.b.a G2;
    public static final e.a.b.c.b.a H;
    public static final e.a.b.c.b.a H0;
    public static final e.a.b.c.b.a H1;
    public static final e.a.b.c.b.a H2;
    public static final e.a.b.c.b.a I;
    public static final e.a.b.c.b.a I0;
    public static final e.a.b.c.b.a I1;
    public static final e.a.b.c.b.a I2;
    public static final e.a.b.c.b.a J;
    public static final e.a.b.c.b.a J0;
    public static final e.a.b.c.b.a J1;
    public static final e.a.b.c.b.a J2;
    public static final e.a.b.c.b.a K;
    public static final e.a.b.c.b.a K0;
    public static final e.a.b.c.b.a K1;
    public static final e.a.b.c.b.a K2;
    public static final e.a.b.c.b.a L;
    public static final e.a.b.c.b.a L0;
    public static final e.a.b.c.b.a L1;
    public static final e.a.b.c.b.a L2;
    public static final e.a.b.c.b.a M;
    public static final e.a.b.c.b.a M0;
    public static final e.a.b.c.b.a M1;
    public static final e.a.b.c.b.a M2;
    public static final e.a.b.c.b.a N;
    public static final e.a.b.c.b.a N0;
    public static final e.a.b.c.b.a N1;
    public static final e.a.b.c.b.a N2;
    public static final e.a.b.c.b.a O;
    public static final e.a.b.c.b.a O0;
    public static final e.a.b.c.b.a O1;
    public static final e.a.b.c.b.a O2;
    public static final e.a.b.c.b.a P;
    public static final e.a.b.c.b.a P0;
    public static final e.a.b.c.b.a P1;
    public static final e.a.b.c.b.a P2;
    public static final e.a.b.c.b.a Q;
    public static final e.a.b.c.b.a Q0;
    public static final e.a.b.c.b.a Q1;
    public static final e.a.b.c.b.a Q2;
    public static final e.a.b.c.b.a R;
    public static final e.a.b.c.b.a R0;
    public static final e.a.b.c.b.a R1;
    public static final e.a.b.c.b.a R2;
    public static final e.a.b.c.b.a S;
    public static final e.a.b.c.b.a S0;
    public static final e.a.b.c.b.a S1;
    public static final e.a.b.c.b.a S2;
    public static final e.a.b.c.b.a T;
    public static final e.a.b.c.b.a T0;
    public static final e.a.b.c.b.a T1;
    public static final e.a.b.c.b.a T2;
    public static final e.a.b.c.b.a U;
    public static final e.a.b.c.b.a U0;
    public static final e.a.b.c.b.a U1;
    public static final e.a.b.c.b.a U2;
    public static final e.a.b.c.b.a V;
    public static final e.a.b.c.b.a V0;
    public static final e.a.b.c.b.a V1;
    public static final e.a.b.c.b.a V2;
    public static final e.a.b.c.b.a W;
    public static final e.a.b.c.b.a W0;
    public static final e.a.b.c.b.a W1;
    public static final e.a.b.c.b.a W2;
    public static final e.a.b.c.b.a X;
    public static final e.a.b.c.b.a X0;
    public static final e.a.b.c.b.a X1;
    public static final e.a.b.c.b.a X2;
    public static final e.a.b.c.b.a Y;
    public static final e.a.b.c.b.a Y0;
    public static final e.a.b.c.b.a Y1;
    public static final e.a.b.c.b.a Y2;
    public static final e.a.b.c.b.a Z;
    public static final e.a.b.c.b.a Z0;
    public static final e.a.b.c.b.a Z1;
    public static final e.a.b.c.b.a Z2;
    public static final e.a.b.c.b.a[] a;
    public static final e.a.b.c.b.a a0;
    public static final e.a.b.c.b.a a1;
    public static final e.a.b.c.b.a a2;
    public static final e.a.b.c.b.a a3;
    public static final e.a.b.c.b.a b;
    public static final e.a.b.c.b.a b0;
    public static final e.a.b.c.b.a b1;
    public static final e.a.b.c.b.a b2;
    public static final e.a.b.c.b.a b3;

    /* renamed from: c, reason: collision with root package name */
    public static final e.a.b.c.b.a f2466c;
    public static final e.a.b.c.b.a c0;
    public static final e.a.b.c.b.a c1;
    public static final e.a.b.c.b.a c2;
    public static final e.a.b.c.b.a c3;

    /* renamed from: d, reason: collision with root package name */
    public static final e.a.b.c.b.a f2467d;
    public static final e.a.b.c.b.a d0;
    public static final e.a.b.c.b.a d1;
    public static final e.a.b.c.b.a d2;
    public static final e.a.b.c.b.a d3;

    /* renamed from: e, reason: collision with root package name */
    public static final e.a.b.c.b.a f2468e;
    public static final e.a.b.c.b.a e0;
    public static final e.a.b.c.b.a e1;
    public static final e.a.b.c.b.a e2;
    public static final e.a.b.c.b.a e3;

    /* renamed from: f, reason: collision with root package name */
    public static final e.a.b.c.b.a f2469f;
    public static final e.a.b.c.b.a f0;
    public static final e.a.b.c.b.a f1;
    public static final e.a.b.c.b.a f2;
    public static final e.a.b.c.b.a f3;

    /* renamed from: g, reason: collision with root package name */
    public static final e.a.b.c.b.a f2470g;
    public static final e.a.b.c.b.a g0;
    public static final e.a.b.c.b.a g1;
    public static final e.a.b.c.b.a g2;
    public static final e.a.b.c.b.a g3;
    public static final e.a.b.c.b.a h;
    public static final e.a.b.c.b.a h0;
    public static final e.a.b.c.b.a h1;
    public static final e.a.b.c.b.a h2;
    public static final e.a.b.c.b.a h3;
    public static final e.a.b.c.b.a i;
    public static final e.a.b.c.b.a i0;
    public static final e.a.b.c.b.a i1;
    public static final e.a.b.c.b.a i2;
    public static final e.a.b.c.b.a i3;
    public static final e.a.b.c.b.a j;
    public static final e.a.b.c.b.a j0;
    public static final e.a.b.c.b.a j1;
    public static final e.a.b.c.b.a j2;
    public static final e.a.b.c.b.a j3;
    public static final e.a.b.c.b.a k;
    public static final e.a.b.c.b.a k0;
    public static final e.a.b.c.b.a k1;
    public static final e.a.b.c.b.a k2;
    public static final e.a.b.c.b.a k3;
    public static final e.a.b.c.b.a l;
    public static final e.a.b.c.b.a l0;
    public static final e.a.b.c.b.a l1;
    public static final e.a.b.c.b.a l2;
    public static final e.a.b.c.b.a l3;
    public static final e.a.b.c.b.a m;
    public static final e.a.b.c.b.a m0;
    public static final e.a.b.c.b.a m1;
    public static final e.a.b.c.b.a m2;
    public static final e.a.b.c.b.a m3;
    public static final e.a.b.c.b.a n;
    public static final e.a.b.c.b.a n0;
    public static final e.a.b.c.b.a n1;
    public static final e.a.b.c.b.a n2;
    public static final e.a.b.c.b.a n3;
    public static final e.a.b.c.b.a o;
    public static final e.a.b.c.b.a o0;
    public static final e.a.b.c.b.a o1;
    public static final e.a.b.c.b.a o2;
    public static final e.a.b.c.b.a o3;
    public static final e.a.b.c.b.a p;
    public static final e.a.b.c.b.a p0;
    public static final e.a.b.c.b.a p1;
    public static final e.a.b.c.b.a p2;
    public static final e.a.b.c.b.a q;
    public static final e.a.b.c.b.a q0;
    public static final e.a.b.c.b.a q1;
    public static final e.a.b.c.b.a q2;
    public static final e.a.b.c.b.a r;
    public static final e.a.b.c.b.a r0;
    public static final e.a.b.c.b.a r1;
    public static final e.a.b.c.b.a r2;
    public static final e.a.b.c.b.a s;
    public static final e.a.b.c.b.a s0;
    public static final e.a.b.c.b.a s1;
    public static final e.a.b.c.b.a s2;
    public static final e.a.b.c.b.a t;
    public static final e.a.b.c.b.a t0;
    public static final e.a.b.c.b.a t1;
    public static final e.a.b.c.b.a t2;
    public static final e.a.b.c.b.a u;
    public static final e.a.b.c.b.a u0;
    public static final e.a.b.c.b.a u1;
    public static final e.a.b.c.b.a u2;
    public static final e.a.b.c.b.a v;
    public static final e.a.b.c.b.a v0;
    public static final e.a.b.c.b.a v1;
    public static final e.a.b.c.b.a v2;
    public static final e.a.b.c.b.a w;
    public static final e.a.b.c.b.a w0;
    public static final e.a.b.c.b.a w1;
    public static final e.a.b.c.b.a w2;
    public static final e.a.b.c.b.a x;
    public static final e.a.b.c.b.a x0;
    public static final e.a.b.c.b.a x1;
    public static final e.a.b.c.b.a x2;
    public static final e.a.b.c.b.a y;
    public static final e.a.b.c.b.a y0;
    public static final e.a.b.c.b.a y1;
    public static final e.a.b.c.b.a y2;
    public static final e.a.b.c.b.a z;
    public static final e.a.b.c.b.a z0;
    public static final e.a.b.c.b.a z1;
    public static final e.a.b.c.b.a z2;

    public static class a {
        public final int a;
        public final java.lang.String b;

        public a(int i, java.lang.String str, e.a.b.c.c.a aVar, e.a.b.c.a aVar2) {
            this.a = i;
            this.b = str;
        }
    }

    static {
        e.a.b.c.a aVar = e.a.b.c.a.STRING_REF;
        e.a.b.c.a aVar2 = e.a.b.c.a.TYPE_REF;
        e.a.b.c.a aVar3 = e.a.b.c.a.METHOD_REF;
        e.a.b.c.a aVar4 = e.a.b.c.a.FIELD_REF;
        e.a.b.c.a aVar5 = e.a.b.c.a.NONE;
        b = new e.a.b.c.b.a(-1, "<special>", e.a.b.c.c.a.a, aVar5);
        f2466c = new e.a.b.c.b.a(256, "packed-switch-payload", e.a.b.c.c.a.G, aVar5);
        f2467d = new e.a.b.c.b.a(512, "sparse-switch-payload", e.a.b.c.c.a.H, aVar5);
        f2468e = new e.a.b.c.b.a(768, "fill-array-data-payload", e.a.b.c.c.a.I, aVar5);
        f2469f = new e.a.b.c.b.a(0, "nop", e.a.b.c.c.a.b, aVar5);
        f2470g = new e.a.b.c.b.a(1, "move", e.a.b.c.c.a.f2471c, aVar5);
        h = new e.a.b.c.b.a(2, "move/from16", e.a.b.c.c.a.i, aVar5);
        i = new e.a.b.c.b.a(3, "move/16", e.a.b.c.c.a.u, aVar5);
        j = new e.a.b.c.b.a(4, "move-wide", e.a.b.c.c.a.f2471c, aVar5);
        k = new e.a.b.c.b.a(5, "move-wide/from16", e.a.b.c.c.a.i, aVar5);
        l = new e.a.b.c.b.a(6, "move-wide/16", e.a.b.c.c.a.u, aVar5);
        m = new e.a.b.c.b.a(7, "move-object", e.a.b.c.c.a.f2471c, aVar5);
        n = new e.a.b.c.b.a(8, "move-object/from16", e.a.b.c.c.a.i, aVar5);
        o = new e.a.b.c.b.a(9, "move-object/16", e.a.b.c.c.a.u, aVar5);
        p = new e.a.b.c.b.a(10, "move-result", e.a.b.c.c.a.f2473e, aVar5);
        q = new e.a.b.c.b.a(11, "move-result-wide", e.a.b.c.c.a.f2473e, aVar5);
        r = new e.a.b.c.b.a(12, "move-result-object", e.a.b.c.c.a.f2473e, aVar5);
        s = new e.a.b.c.b.a(13, "move-exception", e.a.b.c.c.a.f2473e, aVar5);
        t = new e.a.b.c.b.a(14, "return-void", e.a.b.c.c.a.b, aVar5);
        u = new e.a.b.c.b.a(15, "return", e.a.b.c.c.a.f2473e, aVar5);
        v = new e.a.b.c.b.a(16, "return-wide", e.a.b.c.c.a.f2473e, aVar5);
        w = new e.a.b.c.b.a(17, "return-object", e.a.b.c.c.a.f2473e, aVar5);
        x = new e.a.b.c.b.a(18, "const/4", e.a.b.c.c.a.f2472d, aVar5);
        y = new e.a.b.c.b.a(19, "const/16", e.a.b.c.c.a.k, aVar5);
        z = new e.a.b.c.b.a(20, "const", e.a.b.c.c.a.v, aVar5);
        A = new e.a.b.c.b.a(21, "const/high16", e.a.b.c.c.a.l, aVar5);
        B = new e.a.b.c.b.a(22, "const-wide/16", e.a.b.c.c.a.k, aVar5);
        C = new e.a.b.c.b.a(23, "const-wide/32", e.a.b.c.c.a.v, aVar5);
        D = new e.a.b.c.b.a(24, "const-wide", e.a.b.c.c.a.F, aVar5);
        E = new e.a.b.c.b.a(25, "const-wide/high16", e.a.b.c.c.a.l, aVar5);
        F = new e.a.b.c.b.a(26, "const-string", e.a.b.c.c.a.m, aVar);
        G = new e.a.b.c.b.a(27, "const-string/jumbo", e.a.b.c.c.a.x, aVar);
        H = new e.a.b.c.b.a(28, "const-class", e.a.b.c.c.a.m, aVar2);
        I = new e.a.b.c.b.a(29, "monitor-enter", e.a.b.c.c.a.f2473e, aVar5);
        J = new e.a.b.c.b.a(30, "monitor-exit", e.a.b.c.c.a.f2473e, aVar5);
        K = new e.a.b.c.b.a(31, "check-cast", e.a.b.c.c.a.m, aVar2);
        L = new e.a.b.c.b.a(32, "instance-of", e.a.b.c.c.a.r, aVar2);
        M = new e.a.b.c.b.a(33, "array-length", e.a.b.c.c.a.f2471c, aVar5);
        N = new e.a.b.c.b.a(34, "new-instance", e.a.b.c.c.a.m, aVar2);
        O = new e.a.b.c.b.a(35, "new-array", e.a.b.c.c.a.r, aVar2);
        P = new e.a.b.c.b.a(36, "filled-new-array", e.a.b.c.c.a.y, aVar2);
        Q = new e.a.b.c.b.a(37, "filled-new-array/range", e.a.b.c.c.a.B, aVar2);
        R = new e.a.b.c.b.a(38, "fill-array-data", e.a.b.c.c.a.w, aVar5);
        S = new e.a.b.c.b.a(39, "throw", e.a.b.c.c.a.f2473e, aVar5);
        T = new e.a.b.c.b.a(40, "goto", e.a.b.c.c.a.f2474f, aVar5);
        U = new e.a.b.c.b.a(41, "goto/16", e.a.b.c.c.a.f2475g, aVar5);
        V = new e.a.b.c.b.a(42, "goto/32", e.a.b.c.c.a.t, aVar5);
        W = new e.a.b.c.b.a(43, "packed-switch", e.a.b.c.c.a.w, aVar5);
        X = new e.a.b.c.b.a(44, "sparse-switch", e.a.b.c.c.a.w, aVar5);
        Y = new e.a.b.c.b.a(45, "cmpl-float", e.a.b.c.c.a.n, aVar5);
        Z = new e.a.b.c.b.a(46, "cmpg-float", e.a.b.c.c.a.n, aVar5);
        a0 = new e.a.b.c.b.a(47, "cmpl-double", e.a.b.c.c.a.n, aVar5);
        b0 = new e.a.b.c.b.a(48, "cmpg-double", e.a.b.c.c.a.n, aVar5);
        c0 = new e.a.b.c.b.a(49, "cmp-long", e.a.b.c.c.a.n, aVar5);
        d0 = new e.a.b.c.b.a(50, "if-eq", e.a.b.c.c.a.p, aVar5);
        e0 = new e.a.b.c.b.a(51, "if-ne", e.a.b.c.c.a.p, aVar5);
        f0 = new e.a.b.c.b.a(52, "if-lt", e.a.b.c.c.a.p, aVar5);
        g0 = new e.a.b.c.b.a(53, "if-ge", e.a.b.c.c.a.p, aVar5);
        h0 = new e.a.b.c.b.a(54, "if-gt", e.a.b.c.c.a.p, aVar5);
        i0 = new e.a.b.c.b.a(55, "if-le", e.a.b.c.c.a.p, aVar5);
        j0 = new e.a.b.c.b.a(56, "if-eqz", e.a.b.c.c.a.j, aVar5);
        k0 = new e.a.b.c.b.a(57, "if-nez", e.a.b.c.c.a.j, aVar5);
        l0 = new e.a.b.c.b.a(58, "if-ltz", e.a.b.c.c.a.j, aVar5);
        m0 = new e.a.b.c.b.a(59, "if-gez", e.a.b.c.c.a.j, aVar5);
        n0 = new e.a.b.c.b.a(60, "if-gtz", e.a.b.c.c.a.j, aVar5);
        o0 = new e.a.b.c.b.a(61, "if-lez", e.a.b.c.c.a.j, aVar5);
        p0 = new e.a.b.c.b.a(68, "aget", e.a.b.c.c.a.n, aVar5);
        q0 = new e.a.b.c.b.a(69, "aget-wide", e.a.b.c.c.a.n, aVar5);
        r0 = new e.a.b.c.b.a(70, "aget-object", e.a.b.c.c.a.n, aVar5);
        s0 = new e.a.b.c.b.a(71, "aget-boolean", e.a.b.c.c.a.n, aVar5);
        t0 = new e.a.b.c.b.a(72, "aget-byte", e.a.b.c.c.a.n, aVar5);
        u0 = new e.a.b.c.b.a(73, "aget-char", e.a.b.c.c.a.n, aVar5);
        v0 = new e.a.b.c.b.a(74, "aget-short", e.a.b.c.c.a.n, aVar5);
        w0 = new e.a.b.c.b.a(75, "aput", e.a.b.c.c.a.n, aVar5);
        x0 = new e.a.b.c.b.a(76, "aput-wide", e.a.b.c.c.a.n, aVar5);
        y0 = new e.a.b.c.b.a(77, "aput-object", e.a.b.c.c.a.n, aVar5);
        z0 = new e.a.b.c.b.a(78, "aput-boolean", e.a.b.c.c.a.n, aVar5);
        A0 = new e.a.b.c.b.a(79, "aput-byte", e.a.b.c.c.a.n, aVar5);
        B0 = new e.a.b.c.b.a(80, "aput-char", e.a.b.c.c.a.n, aVar5);
        C0 = new e.a.b.c.b.a(81, "aput-short", e.a.b.c.c.a.n, aVar5);
        D0 = new e.a.b.c.b.a(82, "iget", e.a.b.c.c.a.r, aVar4);
        E0 = new e.a.b.c.b.a(83, "iget-wide", e.a.b.c.c.a.r, aVar4);
        F0 = new e.a.b.c.b.a(84, "iget-object", e.a.b.c.c.a.r, aVar4);
        G0 = new e.a.b.c.b.a(85, "iget-boolean", e.a.b.c.c.a.r, aVar4);
        H0 = new e.a.b.c.b.a(86, "iget-byte", e.a.b.c.c.a.r, aVar4);
        I0 = new e.a.b.c.b.a(87, "iget-char", e.a.b.c.c.a.r, aVar4);
        J0 = new e.a.b.c.b.a(88, "iget-short", e.a.b.c.c.a.r, aVar4);
        K0 = new e.a.b.c.b.a(89, "iput", e.a.b.c.c.a.r, aVar4);
        L0 = new e.a.b.c.b.a(90, "iput-wide", e.a.b.c.c.a.r, aVar4);
        M0 = new e.a.b.c.b.a(91, "iput-object", e.a.b.c.c.a.r, aVar4);
        N0 = new e.a.b.c.b.a(92, "iput-boolean", e.a.b.c.c.a.r, aVar4);
        O0 = new e.a.b.c.b.a(93, "iput-byte", e.a.b.c.c.a.r, aVar4);
        P0 = new e.a.b.c.b.a(94, "iput-char", e.a.b.c.c.a.r, aVar4);
        Q0 = new e.a.b.c.b.a(95, "iput-short", e.a.b.c.c.a.r, aVar4);
        R0 = new e.a.b.c.b.a(96, "sget", e.a.b.c.c.a.m, aVar4);
        S0 = new e.a.b.c.b.a(97, "sget-wide", e.a.b.c.c.a.m, aVar4);
        T0 = new e.a.b.c.b.a(98, "sget-object", e.a.b.c.c.a.m, aVar4);
        U0 = new e.a.b.c.b.a(99, "sget-boolean", e.a.b.c.c.a.m, aVar4);
        V0 = new e.a.b.c.b.a(100, "sget-byte", e.a.b.c.c.a.m, aVar4);
        W0 = new e.a.b.c.b.a(101, "sget-char", e.a.b.c.c.a.m, aVar4);
        X0 = new e.a.b.c.b.a(102, "sget-short", e.a.b.c.c.a.m, aVar4);
        Y0 = new e.a.b.c.b.a(103, "sput", e.a.b.c.c.a.m, aVar4);
        Z0 = new e.a.b.c.b.a(104, "sput-wide", e.a.b.c.c.a.m, aVar4);
        a1 = new e.a.b.c.b.a(105, "sput-object", e.a.b.c.c.a.m, aVar4);
        b1 = new e.a.b.c.b.a(106, "sput-boolean", e.a.b.c.c.a.m, aVar4);
        c1 = new e.a.b.c.b.a(107, "sput-byte", e.a.b.c.c.a.m, aVar4);
        d1 = new e.a.b.c.b.a(108, "sput-char", e.a.b.c.c.a.m, aVar4);
        e1 = new e.a.b.c.b.a(109, "sput-short", e.a.b.c.c.a.m, aVar4);
        f1 = new e.a.b.c.b.a(110, "invoke-virtual", e.a.b.c.c.a.y, aVar3);
        g1 = new e.a.b.c.b.a(111, "invoke-super", e.a.b.c.c.a.y, aVar3);
        h1 = new e.a.b.c.b.a(112, "invoke-direct", e.a.b.c.c.a.y, aVar3);
        i1 = new e.a.b.c.b.a(113, "invoke-static", e.a.b.c.c.a.y, aVar3);
        j1 = new e.a.b.c.b.a(114, "invoke-interface", e.a.b.c.c.a.y, aVar3);
        k1 = new e.a.b.c.b.a(116, "invoke-virtual/range", e.a.b.c.c.a.B, aVar3);
        l1 = new e.a.b.c.b.a(117, "invoke-super/range", e.a.b.c.c.a.B, aVar3);
        m1 = new e.a.b.c.b.a(118, "invoke-direct/range", e.a.b.c.c.a.B, aVar3);
        n1 = new e.a.b.c.b.a(119, "invoke-static/range", e.a.b.c.c.a.B, aVar3);
        o1 = new e.a.b.c.b.a(120, "invoke-interface/range", e.a.b.c.c.a.B, aVar3);
        p1 = new e.a.b.c.b.a(123, "neg-int", e.a.b.c.c.a.f2471c, aVar5);
        q1 = new e.a.b.c.b.a(124, "not-int", e.a.b.c.c.a.f2471c, aVar5);
        r1 = new e.a.b.c.b.a(125, "neg-long", e.a.b.c.c.a.f2471c, aVar5);
        s1 = new e.a.b.c.b.a(126, "not-long", e.a.b.c.c.a.f2471c, aVar5);
        t1 = new e.a.b.c.b.a(127, "neg-float", e.a.b.c.c.a.f2471c, aVar5);
        u1 = new e.a.b.c.b.a(128, "neg-double", e.a.b.c.c.a.f2471c, aVar5);
        v1 = new e.a.b.c.b.a(129, "int-to-long", e.a.b.c.c.a.f2471c, aVar5);
        w1 = new e.a.b.c.b.a(130, "int-to-float", e.a.b.c.c.a.f2471c, aVar5);
        x1 = new e.a.b.c.b.a(131, "int-to-double", e.a.b.c.c.a.f2471c, aVar5);
        y1 = new e.a.b.c.b.a(132, "long-to-int", e.a.b.c.c.a.f2471c, aVar5);
        z1 = new e.a.b.c.b.a(133, "long-to-float", e.a.b.c.c.a.f2471c, aVar5);
        A1 = new e.a.b.c.b.a(134, "long-to-double", e.a.b.c.c.a.f2471c, aVar5);
        B1 = new e.a.b.c.b.a(135, "float-to-int", e.a.b.c.c.a.f2471c, aVar5);
        C1 = new e.a.b.c.b.a(136, "float-to-long", e.a.b.c.c.a.f2471c, aVar5);
        D1 = new e.a.b.c.b.a(137, "float-to-double", e.a.b.c.c.a.f2471c, aVar5);
        E1 = new e.a.b.c.b.a(138, "double-to-int", e.a.b.c.c.a.f2471c, aVar5);
        F1 = new e.a.b.c.b.a(139, "double-to-long", e.a.b.c.c.a.f2471c, aVar5);
        G1 = new e.a.b.c.b.a(140, "double-to-float", e.a.b.c.c.a.f2471c, aVar5);
        H1 = new e.a.b.c.b.a(141, "int-to-byte", e.a.b.c.c.a.f2471c, aVar5);
        I1 = new e.a.b.c.b.a(142, "int-to-char", e.a.b.c.c.a.f2471c, aVar5);
        J1 = new e.a.b.c.b.a(143, "int-to-short", e.a.b.c.c.a.f2471c, aVar5);
        K1 = new e.a.b.c.b.a(144, "add-int", e.a.b.c.c.a.n, aVar5);
        L1 = new e.a.b.c.b.a(145, "sub-int", e.a.b.c.c.a.n, aVar5);
        M1 = new e.a.b.c.b.a(146, "mul-int", e.a.b.c.c.a.n, aVar5);
        N1 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.DIV_INT, "div-int", e.a.b.c.c.a.n, aVar5);
        O1 = new e.a.b.c.b.a(148, "rem-int", e.a.b.c.c.a.n, aVar5);
        P1 = new e.a.b.c.b.a(149, "and-int", e.a.b.c.c.a.n, aVar5);
        Q1 = new e.a.b.c.b.a(150, "or-int", e.a.b.c.c.a.n, aVar5);
        R1 = new e.a.b.c.b.a(151, "xor-int", e.a.b.c.c.a.n, aVar5);
        S1 = new e.a.b.c.b.a(152, "shl-int", e.a.b.c.c.a.n, aVar5);
        T1 = new e.a.b.c.b.a(153, "shr-int", e.a.b.c.c.a.n, aVar5);
        U1 = new e.a.b.c.b.a(154, "ushr-int", e.a.b.c.c.a.n, aVar5);
        V1 = new e.a.b.c.b.a(155, "add-long", e.a.b.c.c.a.n, aVar5);
        W1 = new e.a.b.c.b.a(156, "sub-long", e.a.b.c.c.a.n, aVar5);
        X1 = new e.a.b.c.b.a(157, "mul-long", e.a.b.c.c.a.n, aVar5);
        Y1 = new e.a.b.c.b.a(158, "div-long", e.a.b.c.c.a.n, aVar5);
        Z1 = new e.a.b.c.b.a(159, "rem-long", e.a.b.c.c.a.n, aVar5);
        a2 = new e.a.b.c.b.a(160, "and-long", e.a.b.c.c.a.n, aVar5);
        b2 = new e.a.b.c.b.a(161, "or-long", e.a.b.c.c.a.n, aVar5);
        c2 = new e.a.b.c.b.a(162, "xor-long", e.a.b.c.c.a.n, aVar5);
        d2 = new e.a.b.c.b.a(163, "shl-long", e.a.b.c.c.a.n, aVar5);
        e2 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.SHR_LONG, "shr-long", e.a.b.c.c.a.n, aVar5);
        f2 = new e.a.b.c.b.a(165, "ushr-long", e.a.b.c.c.a.n, aVar5);
        g2 = new e.a.b.c.b.a(166, "add-float", e.a.b.c.c.a.n, aVar5);
        h2 = new e.a.b.c.b.a(167, "sub-float", e.a.b.c.c.a.n, aVar5);
        i2 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.MUL_FLOAT, "mul-float", e.a.b.c.c.a.n, aVar5);
        j2 = new e.a.b.c.b.a(169, "div-float", e.a.b.c.c.a.n, aVar5);
        k2 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.REM_FLOAT, "rem-float", e.a.b.c.c.a.n, aVar5);
        l2 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.ADD_DOUBLE, "add-double", e.a.b.c.c.a.n, aVar5);
        m2 = new e.a.b.c.b.a(172, "sub-double", e.a.b.c.c.a.n, aVar5);
        n2 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.MUL_DOUBLE, "mul-double", e.a.b.c.c.a.n, aVar5);
        o2 = new e.a.b.c.b.a(174, "div-double", e.a.b.c.c.a.n, aVar5);
        p2 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.REM_DOUBLE, "rem-double", e.a.b.c.c.a.n, aVar5);
        q2 = new e.a.b.c.b.a(176, "add-int/2addr", e.a.b.c.c.a.f2471c, aVar5);
        r2 = new e.a.b.c.b.a(177, "sub-int/2addr", e.a.b.c.c.a.f2471c, aVar5);
        s2 = new e.a.b.c.b.a(178, "mul-int/2addr", e.a.b.c.c.a.f2471c, aVar5);
        t2 = new e.a.b.c.b.a(179, "div-int/2addr", e.a.b.c.c.a.f2471c, aVar5);
        u2 = new e.a.b.c.b.a(180, "rem-int/2addr", e.a.b.c.c.a.f2471c, aVar5);
        v2 = new e.a.b.c.b.a(181, "and-int/2addr", e.a.b.c.c.a.f2471c, aVar5);
        w2 = new e.a.b.c.b.a(182, "or-int/2addr", e.a.b.c.c.a.f2471c, aVar5);
        x2 = new e.a.b.c.b.a(183, "xor-int/2addr", e.a.b.c.c.a.f2471c, aVar5);
        y2 = new e.a.b.c.b.a(184, "shl-int/2addr", e.a.b.c.c.a.f2471c, aVar5);
        z2 = new e.a.b.c.b.a(185, "shr-int/2addr", e.a.b.c.c.a.f2471c, aVar5);
        A2 = new e.a.b.c.b.a(186, "ushr-int/2addr", e.a.b.c.c.a.f2471c, aVar5);
        B2 = new e.a.b.c.b.a(187, "add-long/2addr", e.a.b.c.c.a.f2471c, aVar5);
        C2 = new e.a.b.c.b.a(188, "sub-long/2addr", e.a.b.c.c.a.f2471c, aVar5);
        D2 = new e.a.b.c.b.a(189, "mul-long/2addr", e.a.b.c.c.a.f2471c, aVar5);
        E2 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.DIV_LONG_2ADDR, "div-long/2addr", e.a.b.c.c.a.f2471c, aVar5);
        F2 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.REM_LONG_2ADDR, "rem-long/2addr", e.a.b.c.c.a.f2471c, aVar5);
        G2 = new e.a.b.c.b.a(192, "and-long/2addr", e.a.b.c.c.a.f2471c, aVar5);
        H2 = new e.a.b.c.b.a(193, "or-long/2addr", e.a.b.c.c.a.f2471c, aVar5);
        I2 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.XOR_LONG_2ADDR, "xor-long/2addr", e.a.b.c.c.a.f2471c, aVar5);
        J2 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.SHL_LONG_2ADDR, "shl-long/2addr", e.a.b.c.c.a.f2471c, aVar5);
        K2 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.SHR_LONG_2ADDR, "shr-long/2addr", e.a.b.c.c.a.f2471c, aVar5);
        L2 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.USHR_LONG_2ADDR, "ushr-long/2addr", e.a.b.c.c.a.f2471c, aVar5);
        M2 = new e.a.b.c.b.a(198, "add-float/2addr", e.a.b.c.c.a.f2471c, aVar5);
        N2 = new e.a.b.c.b.a(199, "sub-float/2addr", e.a.b.c.c.a.f2471c, aVar5);
        O2 = new e.a.b.c.b.a(200, "mul-float/2addr", e.a.b.c.c.a.f2471c, aVar5);
        P2 = new e.a.b.c.b.a(201, "div-float/2addr", e.a.b.c.c.a.f2471c, aVar5);
        Q2 = new e.a.b.c.b.a(202, "rem-float/2addr", e.a.b.c.c.a.f2471c, aVar5);
        R2 = new e.a.b.c.b.a(203, "add-double/2addr", e.a.b.c.c.a.f2471c, aVar5);
        S2 = new e.a.b.c.b.a(204, "sub-double/2addr", e.a.b.c.c.a.f2471c, aVar5);
        T2 = new e.a.b.c.b.a(205, "mul-double/2addr", e.a.b.c.c.a.f2471c, aVar5);
        U2 = new e.a.b.c.b.a(206, "div-double/2addr", e.a.b.c.c.a.f2471c, aVar5);
        V2 = new e.a.b.c.b.a(207, "rem-double/2addr", e.a.b.c.c.a.f2471c, aVar5);
        W2 = new e.a.b.c.b.a(208, "add-int/lit16", e.a.b.c.c.a.q, aVar5);
        X2 = new e.a.b.c.b.a(209, "rsub-int", e.a.b.c.c.a.q, aVar5);
        Y2 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.MUL_INT_LIT16, "mul-int/lit16", e.a.b.c.c.a.q, aVar5);
        Z2 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.DIV_INT_LIT16, "div-int/lit16", e.a.b.c.c.a.q, aVar5);
        a3 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.REM_INT_LIT16, "rem-int/lit16", e.a.b.c.c.a.q, aVar5);
        b3 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.AND_INT_LIT16, "and-int/lit16", e.a.b.c.c.a.q, aVar5);
        c3 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.OR_INT_LIT16, "or-int/lit16", e.a.b.c.c.a.q, aVar5);
        d3 = new e.a.b.c.b.a(215, "xor-int/lit16", e.a.b.c.c.a.q, aVar5);
        e3 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.ADD_INT_LIT8, "add-int/lit8", e.a.b.c.c.a.o, aVar5);
        f3 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.RSUB_INT_LIT8, "rsub-int/lit8", e.a.b.c.c.a.o, aVar5);
        g3 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.MUL_INT_LIT8, "mul-int/lit8", e.a.b.c.c.a.o, aVar5);
        h3 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.DIV_INT_LIT8, "div-int/lit8", e.a.b.c.c.a.o, aVar5);
        i3 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.REM_INT_LIT8, "rem-int/lit8", e.a.b.c.c.a.o, aVar5);
        j3 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.AND_INT_LIT8, "and-int/lit8", e.a.b.c.c.a.o, aVar5);
        k3 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.OR_INT_LIT8, "or-int/lit8", e.a.b.c.c.a.o, aVar5);
        l3 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.XOR_INT_LIT8, "xor-int/lit8", e.a.b.c.c.a.o, aVar5);
        m3 = new e.a.b.c.b.a(224, "shl-int/lit8", e.a.b.c.c.a.o, aVar5);
        n3 = new e.a.b.c.b.a(225, "shr-int/lit8", e.a.b.c.c.a.o, aVar5);
        o3 = new e.a.b.c.b.a(com.tencent.tinker.android.dx.instruction.Opcodes.USHR_INT_LIT8, "ushr-int/lit8", e.a.b.c.c.a.o, aVar5);
        a = new e.a.b.c.b.a[net.easyconn.ecsdk.ECTypes.ECInputType.EC_INPUT_TYPE_TEXT_AUTO_COMPLETE];
        b(b);
        b(f2466c);
        b(f2467d);
        b(f2468e);
        b(f2469f);
        b(f2470g);
        b(h);
        b(i);
        b(j);
        b(k);
        b(l);
        b(m);
        b(n);
        b(o);
        b(p);
        b(q);
        b(r);
        b(s);
        b(t);
        b(u);
        b(v);
        b(w);
        b(x);
        b(y);
        b(z);
        b(A);
        b(B);
        b(C);
        b(D);
        b(E);
        b(F);
        b(G);
        b(H);
        b(I);
        b(J);
        b(K);
        b(L);
        b(M);
        b(N);
        b(O);
        b(P);
        b(Q);
        b(R);
        b(S);
        b(T);
        b(U);
        b(V);
        b(W);
        b(X);
        b(Y);
        b(Z);
        b(a0);
        b(b0);
        b(c0);
        b(d0);
        b(e0);
        b(f0);
        b(g0);
        b(h0);
        b(i0);
        b(j0);
        b(k0);
        b(l0);
        b(m0);
        b(n0);
        b(o0);
        b(p0);
        b(q0);
        b(r0);
        b(s0);
        b(t0);
        b(u0);
        b(v0);
        b(w0);
        b(x0);
        b(y0);
        b(z0);
        b(A0);
        b(B0);
        b(C0);
        b(D0);
        b(E0);
        b(F0);
        b(G0);
        b(H0);
        b(I0);
        b(J0);
        b(K0);
        b(L0);
        b(M0);
        b(N0);
        b(O0);
        b(P0);
        b(Q0);
        b(R0);
        b(S0);
        b(T0);
        b(U0);
        b(V0);
        b(W0);
        b(X0);
        b(Y0);
        b(Z0);
        b(a1);
        b(b1);
        b(c1);
        b(d1);
        b(e1);
        b(f1);
        b(g1);
        b(h1);
        b(i1);
        b(j1);
        b(k1);
        b(l1);
        b(m1);
        b(n1);
        b(o1);
        b(p1);
        b(q1);
        b(r1);
        b(s1);
        b(t1);
        b(u1);
        b(v1);
        b(w1);
        b(x1);
        b(y1);
        b(z1);
        b(A1);
        b(B1);
        b(C1);
        b(D1);
        b(E1);
        b(F1);
        b(G1);
        b(H1);
        b(I1);
        b(J1);
        b(K1);
        b(L1);
        b(M1);
        b(N1);
        b(O1);
        b(P1);
        b(Q1);
        b(R1);
        b(S1);
        b(T1);
        b(U1);
        b(V1);
        b(W1);
        b(X1);
        b(Y1);
        b(Z1);
        b(a2);
        b(b2);
        b(c2);
        b(d2);
        b(e2);
        b(f2);
        b(g2);
        b(h2);
        b(i2);
        b(j2);
        b(k2);
        b(l2);
        b(m2);
        b(n2);
        b(o2);
        b(p2);
        b(q2);
        b(r2);
        b(s2);
        b(t2);
        b(u2);
        b(v2);
        b(w2);
        b(x2);
        b(y2);
        b(z2);
        b(A2);
        b(B2);
        b(C2);
        b(D2);
        b(E2);
        b(F2);
        b(G2);
        b(H2);
        b(I2);
        b(J2);
        b(K2);
        b(L2);
        b(M2);
        b(N2);
        b(O2);
        b(P2);
        b(Q2);
        b(R2);
        b(S2);
        b(T2);
        b(U2);
        b(V2);
        b(W2);
        b(X2);
        b(Y2);
        b(Z2);
        b(a3);
        b(b3);
        b(c3);
        b(d3);
        b(e3);
        b(f3);
        b(g3);
        b(h3);
        b(i3);
        b(j3);
        b(k3);
        b(l3);
        b(m3);
        b(n3);
        b(o3);
    }

    public static java.lang.String a(int i4) {
        try {
            e.a.b.c.b.a aVar = a[i4 + 1];
            if (aVar != null) {
                return aVar.b;
            }
        } catch (java.lang.ArrayIndexOutOfBoundsException unused) {
        }
        java.lang.StringBuilder sbO = e.a.c.a.a.o("bogus opcode: ");
        sbO.append(d.s.y.f0(i4));
        throw new java.lang.IllegalArgumentException(sbO.toString());
    }

    public static void b(e.a.b.c.b.a aVar) {
        a[aVar.a + 1] = aVar;
    }
}
